# Site settings
client: Consumer Reports
title: Digital Standard
email: dev@ocupop.com
url: "https://ocupop.github.io"
permalink: pretty

# Social sharing
description: The Digital Standard is a framework to evaluate consumer technologies and how they respect peopleâ€™s interests and needs.
socialshare:
  featured_image:
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:


# Collections
collections:
  tests:
    output: true
    permalink: /standard/:path

defaults:
  -
    scope:
      type: 'tests'
    values:
      layout: test
      # variable_name: value

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder

test_states: ['1: Green', '2: Yellow', '3: Red']

# Cloudcannon Configuration
_array_structures:
  criteria:
    - label: Criteria
      icon: share
      _options:
        content:
          bold: true
      value:
        criteria_summary:
        indicators:
  indicators:
    - label: Indicators
      icon: share
      value:
        indicator:
        procedure_html:
  test_categories:
    - label: Test Category
      icon: link
      value:
        title:
        tests:

