# Site settings
client: Consumer Reports
title: Digital Standard
email: dev@ocupop.com
# url: "https://ocupop.github.io"
permalink: pretty

# Social sharing
description: The Digital Standard is a framework to evaluate consumer technologies and how they respect peopleâ€™s interests and needs.
socialshare:
  featured_image:
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:


# Collections
collections:
  standards:
    output: true
    permalink: /standard/:path/
  case-studies:
    output: true
    permalink: /case-studies/:path/
    _hide_content: true
    _options:
      content:
        format: p h2 h3 h4 pre
        embed: true

defaults:
  - scope:
      type: 'standards'
    values:
      layout: standard
      # variable_name: value

process_methods:
  - full testing
  - full ratings
  - comparative analysis
  - qualitative interviews

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder

standard_states: ['1: Green', '2: Yellow', '3: Red']
categories:
  - Data Security
  - Build Quality
  - User Safety
  - Access and Control
  - Data Use and Sharing
  - Data retention
  - Overreach - Collecting Too Much Data
  - Ownership
  - Permanence
  - Right to Repair
  - Business Model
  - Human Rights & Corporate Social Responsibility
  - Open
  - Privacy Policy & Terms of Service
  - Transparency

# Cloudcannon Configuration
_array_structures:
  categories:
    - label: Standard Categories
      icon: folder
      value:
        label:
        standards:
  criteria:
    - label: Criteria
      icon: share
      _options:
        content:
          bold: true
      value:
        criteria_summary:
        indicators:
  indicators:
    - label: Indicators
      icon: share
      value:
        indicator:
        procedure_html:

_options:
  layout:
    hidden: true