# Site settings
client: Consumer Reports
title: The Digital Standard
email: digitallab@cr.consumer.org
url: "https://thedigitalstandard.org"
permalink: pretty

# Social sharing
description: The Digital Standard is a framework to evaluate consumer technologies and how they respect peopleâ€™s interests and needs.
socialshare:
  featured_image: /img/socialshare.png
  twitter:
    username:
    image: /img/socialshare.png

# Google Analytics
analytics_code: UA-106357720-14


# Collections
collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/
    _hide_content: true


defaults:
  - scope:
      type: 'case-studies'
    values:
      layout: case-study
      _comments:
        problem: The problem
        process: The process and methods that were used
        impact: The output & impact this had
        who: Who was involved
      _options:
        format: p h2 h3 h4 pre address div
        bold: true
        italic: true
        link: true
        numberedlist: true
        bulletedlist: true
        subscript: true
        superscript: true
        horizontalrule: true
        right: true
        left: true
        center: true
        image: true
        embed: true

process_methods:
  - full testing
  - full ratings
  - comparative analysis
  - qualitative interviews

case_study_status_understandings:
  - Well understood
  - Under development
  - Under discussion


# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss

plugins:
  - jekyll-sitemap
  - jekyll-contentblocks


placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder

areas:
  - Data Security
  - Build Quality
  - User Safety
  - Access and Control
  - Data Use and Sharing
  - Data retention
  - Overreach - Collecting Too Much Data
  - Ownership
  - Interoperability
  - Permanence
  - Right to Repair
  - Business Model
  - Human Rights & Corporate Social Responsibility
  - Open
  - Privacy Policy & Terms of Service
  - Transparency